sudo: required

services:
  - docker

before_install:
  - docker build -f ./dockerfile.dev -t a6596509538/docker_react_frontend:latest.dev .

script:
  - docker run -e CI=true a6596509538/docker_react_frontend:latest.dev npm run test -- --coverage