version: "3"
services:
  redis-server:
    image: "redis"
    ports: 
      - "6379:6379/tcp"
  node-server:
    build: 
      context: .
      dockerfile: dockerfile.dev
    environment:
      - CHOKIDAR_USEPOLLING=true
    ports: 
      - "3000:3000" 
    volumes: 
      - /app/node_modules
      - C:\Users\krzysztof.janowski\Dropbox\Nauka_\docker\projects\frontend_react\frontend_v2:/app
    stdin_open: true
  test-server:
    build: 
      context: .
      dockerfile: dockerfile.dev
    command: ["npm","run","test"]
    stdin_open: true
